eyesight_checker-backend/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  resources :users
  resources :users_tests

  
  # resources :users do
  #   resources :users_tests, only: [:new, :create, :index, :show]
  # end
  # resources :users_tests, only: [:show, :index, :update]

end

eyesight_checker-backend/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

eyesight_checker-backend/app/models/user.rb
class User < ApplicationRecord
    validates :name, presence: true
    validates :email, presence: true, uniqueness: true

    has_many :users_tests
    

end

eyesight_checker-backend/app/models/users_test.rb
class UsersTest < ApplicationRecord
    belongs_to :user
end

eyesight_checker-backend/app/controllers/application_controller.rb
class ApplicationController < ActionController::API
  

    # def current_user
    #     User.find_by(id:session[:user_id])
    # end

    # def logged_in?
    #     !!current_user
    # end

    # def require_login
    #     unless logged_in?
    #       redirect_to root_path
    #     end
    # end

# Methods we built in controller do not permeate to our ActionView. 
# We cannot call it in our html.erb.
# Need to add the folowing:
    # helper_method :current_user    
end

eyesight_checker-backend/app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :set_user, only: [:show, :edit, :update, :destroy]

    def index
        @users = User.all
        render json: @users, status: 200
    end

    def show
        render json: @user, status: 200
    end

    def new
        @user = User.new
    end

    def create
        # byebug
        @user = User.new(user_params)
        if @user.save
            render json: @user, status: :created, location: @user
        else
            render json: @user.errors, status: :unprocessable_entry
        end
    end

    def edit
    end
    
    def update
        if @user.update(user_params)
            render json: @user, status: 200
        else 
            render json: @user.errors, status: :unprocessable_entry
        end
        render json: @user, status: 200
    end

    def destroy
        @user.delete
        render json: {userId: @user.id}
    end

    private

    def set_user
        @user = User.find(params[:id])
    end


    def user_params
        params.require(:user).permit(:name, :email)
    end
    
end

eyesight_checker-backend/app/controllers/users_tests_controller.rb
class UsersTestsController < ApplicationController

    before_action :set_users_test, only: [:show, :edit, :update, :destroy]

    def index
        @users_tests = UsersTest.all
        render json: @users_tests, status: 200
    end

    def show
        render json: @users_test, status: 200
    end

    def new
        @users_test = UsersTest.new
    end

    def create
    # byebug
        @users_test = UsersTest.new(users_test_params)
        if @users_test.save
            render json: @users_test, status: :created, location: @users_test
        else
            render json: @users_test.errors, status: :unprocessable_entry
        end
    end

    def edit
    end

    def update
        if @users_test.update(users_test_params)
            render json: @users_test, status: 200
        else 
            render json: @users_test.errors, status: :unprocessable_entry
        end
    end

    def destroy
        @users_test.delete
        render json: {usersTestId: @users_test.id}
    end

    private

    def set_users_test
        @users_test = UsersTest.find(params[:id])
    end

    def users_test_params
        params.require(:users_test).permit(:test_name, :test_result, :user_id, :users_name)
    end

end

eyesight_checker-backend/app/views/application/welcome.html.erb
<section class="welcome container">
<div class="form-group col-md-12"> 
    <br><h2>Welcome to Online Eyesight Tests </h2>
    <p3> Test your visual acuity from the comfort of your couch or office chair with our online eye test. This test could help give you an indication of whether if you suffer from myopia (short-sightedness), hyperopia (farsightedness) or other eyesight problems that may require corrective glasses or lenses.</p3><br></br> 
    <p3> Please <a href="<%= signin_path %>">Login </a> or <a href="<%= new_user_path %>">Sign Up</a></p3><br></br>
</div>
</section>







   

eyesight_checker-backend/app/views/users/new.htmt.erb
<section class="new-user container">
    <div class="form-group col-md-6"> 
        <h2>Create your account</h2>
        <p><%= @error %></p>
        <%= form_for @user do |f| %>
            <p>Name: <%= f.text_field :name, :class => "form-control" %></p>
            <p>Password: <%= f.text_field :password, :class => "form-control" %></p>
            <p>Email: <%= f.text_field :email, :class => "form-control" %></p>
            <br><%= f.submit "Signup", :class => "btn btn-dark" %>  
        <% end %>
        <br><p>Login with your social media account</p>
        <%= link_to(raw("<i class=\"fab fa-facebook-f\"></i> Facebook"), "/auth/facebook", {:class => "btn btn-lg btn-primary active"}) %> 
    </div>
</section>